package com.googlecode.blaisemath.firestarter;

/*
 * #%L
 * Firestarter
 * --
 * Copyright (C) 2009 - 2014 Elisha Peterson
 * --
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

/*
 * T.java
 *
 * Created on Jun 25, 2009, 11:50:47 AM
 */


import com.googlecode.blaisemath.editor.EditorRegistration;
import com.googlecode.blaisemath.editor.EnumEditor;
import com.googlecode.blaisemath.firestarter.IndexedBean.TestEnum;
import com.googlecode.blaisemath.util.MPanel;
import com.googlecode.blaisemath.util.RollupPanel;
import java.awt.Point;
import java.awt.geom.Point2D;
import java.beans.PropertyEditorManager;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.UIManager;

/**
 *
 * @author ae3263
 */
public class Testing extends javax.swing.JFrame {

    MPanel selectedBeanPanel;

    /** Creates new form T */
    public Testing() {
        try {   UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName()); } catch (Exception e) { }
        EditorRegistration.registerEditors();
        PropertyEditorManager.registerEditor(TestEnum.class, EnumEditor.class);
        PropertyEditorManager.registerEditor(IndexedBean.class, EnumObjectEditor.class);
        PropertySheet.TOOLBAR_VISIBLE_DEFAULT = true;

        initComponents();

        selectedBeanPanel = new MPanel(new JLabel("<html><font size=\"+1\"><b>Selected</b> Bean"), new PropertySheet());
        rollupPanel2.add(selectedBeanPanel);
        rollupPanel2.add("Indexed", PropertySheet.forBean(new IndexedBean()));
        rollupPanel2.add("Indexed B", PropertySheet.forBean(new IndexedBean.Indexed2()));
        rollupPanel2.add("Indexed Strings", IndexedPropertySheet.forIndexedProperty(new IndexedBean(), "strings"));
        PropertySheet ps = PropertySheet.forBean(new CustomBean());
        rollupPanel2.add("Other", ps);
        rollupPanel2.add("Shapes", PropertySheet.forBean(new ShapeBean()));
        // working -
        rollupPanel2.add("Numbers", PropertySheet.forBean(new NumberBean()));
        // working -
        rollupPanel2.add("Points", PropertySheet.forBean(new PointBean()));
        rollupPanel2.add("a Point2D.Double", PropertySheet.forBean(new Point2D.Double(3,4)));
        // working -
        rollupPanel2.add("a Point", PropertySheet.forBean(new Point(3,4)));
        rollupPanel2.add("a text area", new JScrollPane(PropertySheet.forBean(jTextArea1)));

        pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        indexedBean1 = new IndexedBean();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        rollupPanel2 = new RollupPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree(new BeanTreeNode(indexedBean1));
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        JSplitPane center = new JSplitPane();
        getContentPane().add(center, java.awt.BorderLayout.CENTER);
        center.add(jScrollPane2, JSplitPane.RIGHT);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(0.5);
        jSplitPane1.setPreferredSize(new java.awt.Dimension(300, 400));

        jScrollPane3.setViewportView(rollupPanel2);

        jSplitPane1.setBottomComponent(jScrollPane3);

        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree1ValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(jTree1);

        jSplitPane1.setTopComponent(jScrollPane4);

        center.add(jSplitPane1, JSplitPane.LEFT);

        jButton1.setText("jButton1");
        jButton1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel1.add(jButton1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>

    private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {
        Object obj = ((BeanTreeNode)evt.getPath().getLastPathComponent()).getUserObject();
        selectedBeanPanel.setPrimaryComponent(PropertySheet.forBean(obj));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Testing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private IndexedBean indexedBean1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTree jTree1;
    private RollupPanel rollupPanel2;
    // End of variables declaration//GEN-END:variables
}
