import java.awt.geom.AffineTransform
import javax.swing.Icon
import java.awt.Graphics2D
import java.awt.RenderingHints
import java.awt.font.LineMetrics
import java.awt.event.MouseListener
import java.awt.event.MouseMotionListener
import java.awt.event.MouseWheelEvent
import java.awt.event.MouseWheelListener
import java.awt.event.ActionListener
import java.lang.Runnable
import javax.swing.SwingUtilities
import javax.swing.JComponent
import javax.swing.event.AncestorListener
import javax.swing.event.AncestorEvent
import javax.swing.JPopupMenu
import java.util.Arrays
import kotlin.Throws
import java.io.IOException
import java.awt.image.BufferedImage
import javax.imageio.ImageIO
import java.io.ByteArrayInputStream
import java.util.HashSet
import java.io.PrintStream
import java.lang.StringBuilder
import java.beans.PropertyChangeSupport
import java.beans.PropertyChangeListener
import java.awt.Stroke
import java.lang.NumberFormatException
import javax.swing.event.ChangeEvent
import java.util.function.BiConsumer
import java.util.Collections
import kotlin.jvm.JvmOverloads
import java.util.LinkedHashMap
import java.lang.UnsupportedOperationException
import java.lang.IllegalAccessException
import java.lang.reflect.InvocationTargetException
import java.lang.ClassCastException
import java.lang.InstantiationException
import javax.swing.UIManager
import java.beans.BeanInfo
import java.beans.IndexedPropertyDescriptor
import java.lang.NoSuchMethodException
import java.lang.SecurityException
import java.lang.Math
import java.lang.IllegalStateException
import java.awt.geom.GeneralPath
import java.util.ServiceLoader
import java.awt.image.ImageObserver
import java.util.concurrent.ConcurrentMap
import java.util.stream.Collectors
import java.util.EventObject
import com.googlecode.blaisemath.util.ColorsTest
import java.lang.NullPointerException
import junit.framework.TestCase
import com.googlecode.blaisemath.style.AttributeSetCoderTest
import com.googlecode.blaisemath.encode.FontCoderTest
import com.googlecode.blaisemath.encode.ColorCoderTest
import com.googlecode.blaisemath.encode.PointCoderTest
import org.junit.Before