/*
 * PEGApplet.java
 *
 * Created on October 29, 2007, 10:58 AM
 */

package curro;

import analysis.MainVisuals;
import analysis.SimulationLog;
import scio.coordinate.R2;
import sequor.editor.ComboBoxEditor;
import simulation.Simulation;

/**
 *
 * @author  ae3263
 */
public class PEGApplet extends javax.swing.JApplet {
    
    Simulation simulation1;
    SimulationLog dataLog1;
    
    /** Initializes the applet PEGApplet */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    simulation1=new simulation.Simulation();
                    dataLog1 = new analysis.SimulationLog();
                    initComponents();    
                    dataLog1.initialize(simulation1);   
                    plot2D1.add(new MainVisuals(simulation1));
                    plot2D1.getVisometry().setBounds(new R2(-70,-70),new R2(70,70));
                    simulation1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            simulation1ActionPerformed(evt);
                        }
                    });
                    simulationComboBox.setModel(new ComboBoxEditor(simulation1.getGameTypeModel()));
                    simulation1.run();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        simulationComboBox = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        resetButton = new javax.swing.JButton();
        runButton = new javax.swing.JButton();
        simulationSettingsPanel1 = new applications.SimulationSettingsPanel(simulation1.ss);
        plot2D1 = new specto.euclidean2.Plot2D();

        jSplitPane2.setDividerLocation(350);

        jToolBar1.setFloatable(false);

        jLabel1.setText("Scenario:");
        jToolBar1.add(jLabel1);

        simulationComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        simulationComboBox.setMaximumSize(new java.awt.Dimension(150, 20));
        jToolBar1.add(simulationComboBox);
        jToolBar1.add(jSeparator1);

        resetButton.setFont(new java.awt.Font("Tahoma", 1, 14));
        resetButton.setText("RESET");
        resetButton.setToolTipText("Click here to reset the simulation and re-randomize starting positions.");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(resetButton);

        runButton.setFont(new java.awt.Font("Tahoma", 1, 14));
        runButton.setText("RUN!!");
        runButton.setToolTipText("Click here to run the simulation again.");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(runButton);

        simulationSettingsPanel1.setDividerLocation(100);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
            .addComponent(simulationSettingsPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(simulationSettingsPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(jPanel1);

        javax.swing.GroupLayout plot2D1Layout = new javax.swing.GroupLayout(plot2D1);
        plot2D1.setLayout(plot2D1Layout);
        plot2D1Layout.setHorizontalGroup(
            plot2D1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        plot2D1Layout.setVerticalGroup(
            plot2D1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        jSplitPane2.setRightComponent(plot2D1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void simulation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulation1ActionPerformed
        //System.out.println("action performed: "+evt.getActionCommand());
        if(evt.getActionCommand().equals("redraw")){
            plot2D1.repaint();
        }
        else if(evt.getActionCommand().equals("recolor")){
            plot2D1.repaint();
            simulationSettingsPanel1.repaint();
        }
        // simulation has changed in some fundamental way
        else if(evt.getActionCommand().equals("reset")){
            plot2D1.clearPlottables();
            plot2D1.rebuildOptionsMenu();
            dataLog1.initialize(simulation1);   
            plot2D1.add(new MainVisuals(simulation1));
        }
    }//GEN-LAST:event_simulation1ActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        simulation1.initStartingLocations();
        simulation1.run();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        simulation1.run();
    }//GEN-LAST:event_runButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JToolBar jToolBar1;
    private specto.euclidean2.Plot2D plot2D1;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton runButton;
    private javax.swing.JComboBox simulationComboBox;
    private applications.SimulationSettingsPanel simulationSettingsPanel1;
    // End of variables declaration//GEN-END:variables
        
}
