package com.googlecode.blaisemath.palette.ui

import com.googlecode.blaisemath.firestarter.editor.EditorRegistration
import com.googlecode.blaisemath.palette.ColorSchemes
import com.googlecode.blaisemath.palette.MapPalette
import com.googlecode.blaisemath.palette.Palettes
import java.awt.EventQueue
import java.awt.GridLayout
import java.beans.PropertyChangeEvent
import java.beans.PropertyChangeListener
import java.util.logging.Level
import java.util.logging.Logger
import javax.swing.JFrame
import javax.swing.JLabel
import javax.swing.UIManager
import javax.swing.UnsupportedLookAndFeelException

/*
* #%L
* blaise-graphics
* --
* Copyright (C) 2019 - 2021 Elisha Peterson
* --
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
* #L%
*/   class PaletteEditorTestUi : JFrame() {
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private fun initComponents() {
        preview = ColorListIcon()
        palette = MapPalette()
        gradientPreview = ColorSchemeGradientIcon()
        schemePreview = ColorListIcon()
        editor = PaletteEditor()
        jLabel1 = JLabel()
        gradientEditor = ColorSchemeEditor()
        jLabel2 = JLabel()
        schemeEditor = ColorSchemeEditor()
        jLabel3 = JLabel()
        preview.setPalette(palette)
        schemePreview.setPalette(palette)
        defaultCloseOperation = EXIT_ON_CLOSE
        contentPane.layout = GridLayout(1, 2)
        editor.setPalette(palette)
        contentPane.add(editor)
        jLabel1.setIcon(preview)
        contentPane.add(jLabel1)
        contentPane.add(gradientEditor)
        jLabel2.setIcon(gradientPreview)
        contentPane.add(jLabel2)
        contentPane.add(schemeEditor)
        jLabel3.setIcon(schemePreview)
        contentPane.add(jLabel3)
        pack()
    } // </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private var editor: PaletteEditor? = null
    private var gradientEditor: ColorSchemeEditor? = null
    private var gradientPreview: ColorSchemeGradientIcon? = null
    private var jLabel1: JLabel? = null
    private var jLabel2: JLabel? = null
    private var jLabel3: JLabel? = null
    private var palette: MapPalette? = null
    private var preview: ColorListIcon? = null
    private var schemeEditor: ColorSchemeEditor? = null
    private var schemePreview: ColorListIcon? = null // End of variables declaration//GEN-END:variables

    companion object {
        /**
         * @param args the command line arguments
         */
        @JvmStatic
        fun main(args: Array<String>) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
            try {
                for (info in UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus" == info.name) {
                        UIManager.setLookAndFeel(info.className)
                        break
                    }
                }
            } catch (ex: ClassNotFoundException) {
                Logger.getLogger(PaletteEditorTestUi::class.java.name).log(Level.SEVERE, null, ex)
            } catch (ex: UnsupportedLookAndFeelException) {
                Logger.getLogger(PaletteEditorTestUi::class.java.name).log(Level.SEVERE, null, ex)
            } catch (ex: IllegalAccessException) {
                Logger.getLogger(PaletteEditorTestUi::class.java.name).log(Level.SEVERE, null, ex)
            } catch (ex: InstantiationException) {
                Logger.getLogger(PaletteEditorTestUi::class.java.name).log(Level.SEVERE, null, ex)
            }
            //</editor-fold>

            /* Create and display the form */EventQueue.invokeLater { PaletteEditorTestUi().isVisible = true }
        }
    }

    init {
        initComponents()
        EditorRegistration.registerEditors()
        val pal = Palettes.defaultPalette().mutableCopy()
        editor.setPalette(pal)
        preview.setPalette(pal)
        preview.setColors(editor.getColorListModel())
        editor.addColorListPropertyChangeListener(PropertyChangeListener { evt: PropertyChangeEvent? ->
            jLabel1.repaint()
            jLabel2.repaint()
            jLabel3.repaint()
        })
        val grad = ColorSchemes.scheme("BLUES").get()
        gradientEditor.setScheme(grad)
        gradientPreview.setPalette(pal)
        gradientPreview.setScheme(grad)
        gradientEditor.addColorListPropertyChangeListener(PropertyChangeListener { evt: PropertyChangeEvent? -> jLabel2.repaint() })
        val sch2 = ColorSchemes.scheme("CATEGORY20").get()
        schemeEditor.setScheme(sch2)
        schemePreview.setPalette(pal)
        schemePreview.setColors(schemeEditor.getColorListModel())
        schemePreview.setShowNames(false)
        schemeEditor.addColorListPropertyChangeListener(PropertyChangeListener { evt: PropertyChangeEvent? -> jLabel3.repaint() })
    }
}