import java.util.ServiceLoader
import kotlin.Throws
import java.io.IOException
import java.lang.IllegalAccessException
import java.lang.reflect.InvocationTargetException
import java.lang.NoSuchMethodException
import java.awt.Graphics2D
import java.awt.Dimension
import java.awt.geom.AffineTransform
import java.text.DecimalFormat
import java.lang.StringBuilder
import java.lang.NumberFormatException
import kotlin.jvm.JvmOverloads
import java.util.Arrays
import java.lang.Runnable
import javax.swing.SwingUtilities
import java.util.stream.Collectors
import java.util.LinkedHashSet
import javax.swing.JPopupMenu
import java.awt.Stroke
import java.awt.font.FontRenderContext
import java.awt.font.GlyphVector
import java.awt.geom.GeneralPath
import java.awt.RenderingHints
import java.util.concurrent.ExecutionException
import java.util.concurrent.TimeUnit
import java.awt.image.BufferedImage
import java.awt.GradientPaint
import java.awt.AlphaComposite
import javax.swing.Icon
import java.awt.event.MouseListener
import java.awt.event.MouseMotionListener
import javax.swing.event.PopupMenuListener
import javax.swing.event.PopupMenuEvent
import javax.swing.JComponent
import java.lang.IllegalStateException
import java.awt.event.MouseAdapter
import java.awt.event.MouseWheelEvent
import java.beans.PropertyChangeListener
import java.beans.PropertyChangeEvent
import java.beans.PropertyChangeSupport
import java.util.Collections
import java.util.HashSet
import com.googlecode.blaisemath.graphics.svg.SvgPathCoderTest
import junit.framework.TestCase
import javax.swing.JFrame
import javax.swing.JLabel
import kotlin.jvm.JvmStatic
import com.googlecode.blaisemath.graphics.swing.TooltipTestFrame
import com.googlecode.blaisemath.graphics.swing.SelectionTestFrame
import com.googlecode.blaisemath.graphics.swing.HelloWorldTestFrame
import com.googlecode.blaisemath.graphics.swing.PanAndZoomTestFrame
import com.googlecode.blaisemath.graphics.swing.ContextMenuTestFrame
import javax.swing.AbstractAction
import com.googlecode.blaisemath.graphics.swing.ClippedImageTestFrame