/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BlaisePagePanelPlus.java
 *
 * Created on Dec 31, 2009, 1:54:00 PM
 */

package org.bm.blaise.scribo.page;

import data.propertysheet.PropertySheet;
import data.propertysheet.editor.FunctionEditor;
import org.bm.blaise.specto.visometry.PlotComponent;
import org.bm.blaise.specto.visometry.Plottable;

/**
 *
 * @author ae3263
 */
public class BlaisePagePanelPlus extends javax.swing.JPanel {

    /** Creates new form BlaisePagePanelPlus */
    public BlaisePagePanelPlus() {
        initComponents();

        // ensure editors are registered
//        data.beans.EditorRegistration.registerEditors();
//        FunctionEditor.register();
    }

    public BlaisePage getPage() {
        return blaisePagePanel1.getPage();
    }

    public void setPage(BlaisePage page) {
        blaisePagePanel1.setPage(page);
        PlotComponent<?> newPlot = getPage().getActivePlot();
        rollupPanel1.removeAll();
        if (newPlot != null) {
            rollupPanel1.add("Visometry", new PropertySheet(newPlot.getVisometry()));
            for (Plottable p : newPlot.getPlottables()) {
                rollupPanel1.add(p.toString(), new PropertySheet(p));
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        blaisePagePanel1 = new org.bm.blaise.scribo.page.BlaisePagePanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rollupPanel1 = new gui.RollupPanel();

        jSplitPane1.setDividerLocation(300);
        jSplitPane1.setDividerSize(8);
        jSplitPane1.setResizeWeight(0.75);
        jSplitPane1.setContinuousLayout(true);
        jSplitPane1.setOneTouchExpandable(true);

        blaisePagePanel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blaisePagePanel1ActionPerformed(evt);
            }
        });
        blaisePagePanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                blaisePagePanel1ComponentShown(evt);
            }
        });
        jSplitPane1.setLeftComponent(blaisePagePanel1);

        jScrollPane1.setViewportView(rollupPanel1);

        jSplitPane1.setRightComponent(jScrollPane1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void blaisePagePanel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blaisePagePanel1ActionPerformed
        // this automatically updates the settings panel whenever the selected plot changes
        if (evt.getActionCommand().equals("PLOT CHANGE")) {
            PlotComponent<?> newPlot = getPage().getActivePlot();
            rollupPanel1.removeAll();
            if (newPlot != null) {
                rollupPanel1.add("Visometry", new PropertySheet(newPlot.getVisometry()));
                for (Plottable p : newPlot.getPlottables()) {
                    rollupPanel1.add(p.toString(), new PropertySheet(p));
                }
            }
        }
    }//GEN-LAST:event_blaisePagePanel1ActionPerformed

    private void blaisePagePanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_blaisePagePanel1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_blaisePagePanel1ComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.bm.blaise.scribo.page.BlaisePagePanel blaisePagePanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private gui.RollupPanel rollupPanel1;
    // End of variables declaration//GEN-END:variables

}
