/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DemoLineVisometry.java
 *
 * Created on May 12, 2010, 7:46:47 AM
 */

package gtest;

import data.propertysheet.PropertySheet;
import java.awt.BasicStroke;
import java.awt.Color;
import primitive.style.PathStylePoints;
import visometry.line.LineFunction;
import visometry.line.LinePlotComponent;
import visometry.line.TimelinePlot;
import visometry.plottable.VPoint;
import visometry.plottable.VSegment;

/**
 *
 * @author ae3263
 */
public class DemoLineVisometry extends javax.swing.JFrame {

    LinePlotComponent l1, l2, l3;
    TimelinePlot l4;

    /** Creates new form DemoLineVisometry */
    public DemoLineVisometry() {
        data.propertysheet.editor.EditorRegistration.registerEditors();
        
        initComponents();

        tabs.add("Basic", l1 = new LinePlotComponent());
        tabs.add("Generic", l2 = new LinePlotComponent());
        tabs.add("Function", l3 = new LinePlotComponent());
        tabs.add("Timeline", l4 = new TimelinePlot());

        props.add("Visometry 1", new PropertySheet(l1.getVisometry()));
        props.add("Axis 1", new PropertySheet(l1.getAxis()));

        LineFunction lf;
        l3.add(lf = new LineFunction());
        props.add("Function 3", new PropertySheet(lf));

        VPoint<Double> p1;
        l4.add(p1 = new VPoint<Double>(0.0));
        props.add("Timeline Axis 4", new PropertySheet(l4.getAxis()));
        props.add("Point 4", new PropertySheet(p1));
        VSegment seg1 = new VSegment<Double>(0.1, 0.78);
        PathStylePoints segStyle = new PathStylePoints(Color.yellow);
        segStyle.setStroke(new BasicStroke(60f, BasicStroke.CAP_BUTT, BasicStroke.JOIN_MITER));
        segStyle.setStrokeOpacity(.5f);
        seg1.setStrokeStyle(segStyle);
        l4.add(seg1);
        props.add("Segment", new PropertySheet(seg1));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        props = new gui.RollupPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Line Visometry Test");

        tabs.setPreferredSize(new java.awt.Dimension(500, 400));
        getContentPane().add(tabs, java.awt.BorderLayout.CENTER);
        getContentPane().add(props, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DemoLineVisometry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.RollupPanel props;
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables

}
