package com.googlecode.blaisemath.graphics.swing;

/*-
 * #%L
 * blaise-graphics
 * --
 * Copyright (C) 2009 - 2019 Elisha Peterson
 * --
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import com.googlecode.blaisemath.graphics.PrimitiveGraphic;
import com.googlecode.blaisemath.graphics.swing.render.ClippedImageRenderer;
import com.googlecode.blaisemath.primitive.ClippedImage;
import com.googlecode.blaisemath.style.Styles;

import java.awt.*;
import java.awt.geom.Ellipse2D;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class ClippedImageTestUi extends javax.swing.JFrame {

    public ClippedImageTestUi() {
        try {
            initComponents();
            JGraphicComponent canvas = new JGraphicComponent();
            canvas.setBackground(Color.black);
            PanAndZoomHandler.install(canvas);
            ClippedImage image = new ClippedImage(getClass().getResource("resources/torus.png"), new Ellipse2D.Double(5, 5, 300, 300));
            PrimitiveGraphic<ClippedImage, Graphics2D> pg1 = new PrimitiveGraphic<>(image, Styles.strokeWidth(Color.red, 2f),
                    new ClippedImageRenderer());
            canvas.addGraphic(pg1);
            setContentPane(canvas);
            pack();
        } catch (IOException ex) {
            Logger.getLogger(ClippedImageTestUi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(() -> new ClippedImageTestUi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
