/*
 * TestPlaneVisometry.java
 *
 * Created on Jul 30, 2009, 3:15:03 PM
 */
package org.bm.blaise.testing.plane;

import data.propertysheet.PropertySheet;
import data.propertysheet.editor.EditorRegistration;
import org.bm.blaise.scio.graph.PreferentialAttachment;
import org.bm.blaise.scio.graph.RandomGraph;
import org.bm.blaise.scio.graph.layout.SpringLayout;
import org.bm.blaise.scio.graph.layout.StaticGraphLayout;
import org.bm.blaise.scio.graph.time.TimeGraph;
import org.bm.blaise.specto.plane.graph.GraphManager;
import org.bm.blaise.specto.plane.graph.PlaneGraphAdapter;
import org.bm.blaise.specto.plane.graph.time.TimeGraphManager;

/**
 *
 * @author ae3263
 */
public class TestTimeGraph extends javax.swing.JFrame {

    TimeGraphManager tgm;
    GraphManager gm;
    PlaneGraphAdapter pga;
    /** Flag for when el needs points updated */
    boolean updateEL = true;
    SpringLayout energyLayout;

    /** Creates new form TestPlaneVisometry */
    public TestTimeGraph() {
        EditorRegistration.registerEditors();
        initComponents();
        // BASIC ELEMENTS
        TimeGraph<Integer> g = PreferentialAttachment.getTimeSeededInstance(
                RandomGraph.getInstance(10, 10, false),
                70, new float[]{0,1f,.00f});
        tgm = new TimeGraphManager(g);
        plot.setManager(tgm);
        gm = plot.getGraphComponent().getGraphManager();

        // PANELS

        rollupPanel1.add("Visometry", new PropertySheet(plot.getGraphComponent().getVisometry()));
        rollupPanel1.add("Nodes", new PropertySheet(plot.getGraphComponent().getAdapter().getNodeRenderer()));
        rollupPanel1.add("Edges", new PropertySheet(plot.getGraphComponent().getAdapter().getEdgeRenderer()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        randomLB = new javax.swing.JButton();
        circleLB = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        energyIB = new javax.swing.JButton();
        energyAB = new javax.swing.JButton();
        energySB = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jLabel2 = new javax.swing.JLabel();
        energyIB1 = new javax.swing.JButton();
        energyAB1 = new javax.swing.JButton();
        energySB1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        rollupPanel1 = new gui.RollupPanel();
        plot = new org.bm.blaise.specto.plane.graph.time.TimeGraphComponent();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jToolBar1.setRollover(true);

        randomLB.setText("Random Layout");
        randomLB.setFocusable(false);
        randomLB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        randomLB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        randomLB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomLBActionPerformed(evt);
            }
        });
        jToolBar1.add(randomLB);

        circleLB.setText("Circle Layout");
        circleLB.setFocusable(false);
        circleLB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        circleLB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        circleLB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circleLBActionPerformed(evt);
            }
        });
        jToolBar1.add(circleLB);
        jToolBar1.add(jSeparator1);

        jLabel1.setText("ENERGY:");
        jToolBar1.add(jLabel1);

        energyIB.setText("iterate");
        energyIB.setFocusable(false);
        energyIB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        energyIB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        energyIB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                energyIBActionPerformed(evt);
            }
        });
        jToolBar1.add(energyIB);

        energyAB.setText("animate");
        energyAB.setFocusable(false);
        energyAB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        energyAB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        energyAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                energyABActionPerformed(evt);
            }
        });
        jToolBar1.add(energyAB);

        energySB.setText("stop");
        energySB.setFocusable(false);
        energySB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        energySB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        energySB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                energySBActionPerformed(evt);
            }
        });
        jToolBar1.add(energySB);
        jToolBar1.add(jSeparator2);

        jLabel2.setText("SIMUL:");
        jToolBar1.add(jLabel2);

        energyIB1.setText("iterate");
        energyIB1.setFocusable(false);
        energyIB1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        energyIB1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        energyIB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                energyIB1ActionPerformed(evt);
            }
        });
        jToolBar1.add(energyIB1);

        energyAB1.setText("animate");
        energyAB1.setFocusable(false);
        energyAB1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        energyAB1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        energyAB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                energyAB1ActionPerformed(evt);
            }
        });
        jToolBar1.add(energyAB1);

        energySB1.setText("stop");
        energySB1.setFocusable(false);
        energySB1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        energySB1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        energySB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                energySB1ActionPerformed(evt);
            }
        });
        jToolBar1.add(energySB1);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setViewportView(rollupPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.EAST);
        getContentPane().add(plot, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void randomLBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomLBActionPerformed
        updateEL = true;
        gm.applyLayout(StaticGraphLayout.RANDOM, 5.0);
    }//GEN-LAST:event_randomLBActionPerformed

    private void circleLBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circleLBActionPerformed
        updateEL = true;
        gm.applyLayout(StaticGraphLayout.CIRCLE, 5.0);
    }//GEN-LAST:event_circleLBActionPerformed

    private void energyIBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_energyIBActionPerformed
        if (energyLayout == null)
            energyLayout = new SpringLayout(gm.getNodePositions());
        gm.setLayoutAlgorithm(energyLayout);
        gm.iterateLayout();
        updateEL = false;
    }//GEN-LAST:event_energyIBActionPerformed

    private void energyABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_energyABActionPerformed
        if (energyLayout == null)
            energyLayout = new SpringLayout(gm.getNodePositions());
        gm.setLayoutAlgorithm(energyLayout);
        gm.startLayoutTask(10, 2);
    }//GEN-LAST:event_energyABActionPerformed

    private void energySBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_energySBActionPerformed
        gm.stopLayoutTask();
    }//GEN-LAST:event_energySBActionPerformed

    private void energyIB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_energyIB1ActionPerformed
        if (energyLayout == null)
            energyLayout = new SpringLayout(gm.getNodePositions());
        tgm.iterateLayout();
        updateEL = false;
    }//GEN-LAST:event_energyIB1ActionPerformed

    private void energyAB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_energyAB1ActionPerformed
        if (energyLayout == null)
            energyLayout = new SpringLayout(gm.getNodePositions());
        tgm.startLayoutTask(10, 2);
    }//GEN-LAST:event_energyAB1ActionPerformed

    private void energySB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_energySB1ActionPerformed
        tgm.stopLayoutTask();
    }//GEN-LAST:event_energySB1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TestTimeGraph().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton circleLB;
    private javax.swing.JButton energyAB;
    private javax.swing.JButton energyAB1;
    private javax.swing.JButton energyIB;
    private javax.swing.JButton energyIB1;
    private javax.swing.JButton energySB;
    private javax.swing.JButton energySB1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private org.bm.blaise.specto.plane.graph.time.TimeGraphComponent plot;
    private javax.swing.JButton randomLB;
    private gui.RollupPanel rollupPanel1;
    // End of variables declaration//GEN-END:variables
}
