/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.blaise.graphics;

import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Rectangle2D;
import java.util.Set;
import javax.swing.AbstractAction;
import javax.swing.JPopupMenu;

/**
 *
 * @author Elisha
 */
public class TestMenu extends javax.swing.JFrame {

    /**
     * Creates new form TestTooltips
     */
    public TestMenu() {
        initComponents();
        BasicShapeGraphic g1 = new BasicShapeGraphic(new Ellipse2D.Double(50,50,100,100));
        g1.addContextMenuInitializer(new ContextMenuInitializer(){
            public void initialize(JPopupMenu menu, Point point, Object focus, Set<Graphic> selection) {
                menu.add(""+point);
                menu.add(new AbstractAction("press me"){
                    public void actionPerformed(ActionEvent e) { System.out.println("pressed"); }
                });
            }
        });
        gc.addGraphic(g1);
        
        BasicShapeGraphic g2 = new BasicShapeGraphic(new Rectangle2D.Double(60,90,100,100));
        gc.addGraphic(g2);
        
        gc.setSelectionEnabled(true);
        gc.getGraphicRoot().addContextMenuInitializer(new ContextMenuInitializer(){
            public void initialize(JPopupMenu menu, Point point, Object focus, Set<Graphic> selection) {
                menu.setLabel("root label");
                menu.add((selection == null ? 0 : selection.size()) + " graphics selected");
                if (menu.getComponentCount() > 0)
                    menu.addSeparator();
                menu.add("Root menu option");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gc = new org.blaise.graphics.GraphicComponent();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.layout.GroupLayout gcLayout = new org.jdesktop.layout.GroupLayout(gc);
        gc.setLayout(gcLayout);
        gcLayout.setHorizontalGroup(
            gcLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 404, Short.MAX_VALUE)
        );
        gcLayout.setVerticalGroup(
            gcLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(gc, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.blaise.graphics.GraphicComponent gc;
    // End of variables declaration//GEN-END:variables
}
