/*
 * Copyright 2017 elisha.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.googlecode.blaisemath.palette;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.googlecode.blaisemath.graphics.core.PrimitiveGraphic;
import com.googlecode.blaisemath.graphics.swing.JGraphics;
import com.googlecode.blaisemath.graphics.swing.ShapeRenderer;
import com.googlecode.blaisemath.json.AwtJson;
import com.googlecode.blaisemath.style.AttributeSet;
import com.googlecode.blaisemath.style.Styles;
import java.awt.Graphics2D;
import java.awt.LinearGradientPaint;
import java.awt.Paint;
import java.awt.Shape;
import java.awt.geom.Point2D;
import java.awt.geom.Rectangle2D;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author elisha
 */
public class GradientPaletteTestUi extends javax.swing.JFrame {
    
    PrimitiveGraphic<Point2D,Graphics2D> pt1, pt2;
    PrimitiveGraphic<Shape,Graphics2D> gfc;
    LinearGradientPaint lgp;

    /**
     * Creates new form GradientPaletteTestUi
     */
    public GradientPaletteTestUi() {
        initComponents();
        
        Rectangle2D.Double rect = new Rectangle2D.Double();
        rect.setFrameFromDiagonal(randomPoint(), randomPoint());
        gfc = JGraphics.shape(rect, Styles.defaultShapeStyle());
        canvas.addGraphic(gfc);
        
        pt1 = JGraphics.point(randomPoint(), Styles.defaultShapeStyle());
        pt1.setDragEnabled(true);
        canvas.addGraphic(pt1);
        
        pt2 = JGraphics.point(randomPoint(), Styles.defaultShapeStyle());
        pt2.setDragEnabled(true);
        canvas.addGraphic(pt2);
        
        setGradient(new GradientPalette());
    }
    
    private void setGradient(GradientPalette gp) {
        Paint paint = gp.linearGradientPaint(pt1.getPrimitive(), pt2.getPrimitive());
        gfc.setRenderer(new ShapeRenderer(){
            @Override
            public void render(Shape primitive, AttributeSet style, Graphics2D canvas) {
                canvas.setPaint(paint);
                canvas.fill(primitive);

                if (Styles.hasStroke(style)) {
                    canvas.setColor(Styles.strokeColorOf(style));
                    canvas.setStroke(Styles.strokeOf(style));
                    canvas.draw(primitive);
                }
            }
        });
    }
    
    private Point2D randomPoint() {
        return new Point2D.Double(Math.random()*canvas.getWidth(), Math.random()*canvas.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        canvas = new com.googlecode.blaisemath.graphics.swing.JGraphicComponent();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(600);

        text.setColumns(20);
        text.setRows(5);
        text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(text);

        jSplitPane1.setRightComponent(jScrollPane1);
        jSplitPane1.setLeftComponent(canvas);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        jToolBar1.setRollover(true);

        jButton1.setText("jButton1");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textKeyReleased
        try {
            ObjectMapper mapper = new ObjectMapper();
            mapper.registerModule(AwtJson.module());
            setGradient(mapper.readValue(text.getText(), GradientPalette.class));
        } catch (IOException ex) {
            Logger.getLogger(GradientPaletteTestUi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_textKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GradientPaletteTestUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GradientPaletteTestUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GradientPaletteTestUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GradientPaletteTestUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GradientPaletteTestUi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.googlecode.blaisemath.graphics.swing.JGraphicComponent canvas;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextArea text;
    // End of variables declaration//GEN-END:variables

}
