/*
 * TestPlaneVisometry.java
 *
 * Created on Jul 30, 2009, 3:15:03 PM
 */
package org.bm.blaise.testing.plane;

import org.bm.blaise.specto.plottable.VLine;
import org.bm.blaise.specto.plottable.VPoint;
import org.bm.blaise.specto.plottable.VPath;
import org.bm.blaise.specto.plottable.VRectangle;
import org.bm.blaise.specto.plottable.VLabel;
import org.bm.blaise.specto.plane.function.PlaneFunctionGraph;
import data.propertysheet.PropertySheet;
import java.awt.geom.Point2D;
import org.apache.commons.math.FunctionEvaluationException;
import org.apache.commons.math.analysis.UnivariateRealFunction;
import org.bm.blaise.specto.plane.*;
import org.bm.blaise.specto.plane.function.PlaneParametricFunction2;
import org.bm.blaise.specto.visometry.Plottable;
import scio.function.MultivariateVectorialFunction;

/**
 *
 * @author ae3263
 */
public class TestBasicPlane extends javax.swing.JFrame {

    /** Creates new form TestPlaneVisometry */
    public TestBasicPlane() {
        data.beans.EditorRegistration.registerEditors();
        initComponents();


        // BASIC ELEMENTS

        basicPlot.addPlottable(new VPoint<Point2D.Double>(new Point2D.Double(.2, -.2)));
        basicPlot.addPlottable(new VRectangle<Point2D.Double>(new Point2D.Double(.5, -2), new Point2D.Double(1, -1)));
        basicPlot.addPlottable(new VPath<Point2D.Double>(new Point2D.Double[]{
                    new Point2D.Double(-.5, 1.1), new Point2D.Double(-.5, 2.1), new Point2D.Double(-1.0, 0.7)
                }));
        basicPlot.addPlottable(new VLine<Point2D.Double>(new Point2D.Double(1, 0), new Point2D.Double(0, 1)));
        basicPlot.addPlottable(new VLabel<Point2D.Double>(new Point2D.Double(2.5, 1.0), "Label!"));
        basicPlot.setDesiredRange(-5.0, -5.0, 5.0, 5.0);

        // FUNCTIONS

        funPlot.addPlottable(new PlaneGrid());
        funPlot.addPlottable(new PlaneAxes());
        funPlot.addPlottable(new PlaneFunctionGraph(new UnivariateRealFunction() {
            public double value(double x) throws FunctionEvaluationException {
                return Math.cos(x);
            }
        }));
        funPlot.setDesiredRange(-5.0, -1.0, 5.0, 1.0);

        funPlot2.addPlottable(new PlaneGrid());
        funPlot2.addPlottable(new PlaneAxes());
        funPlot2.addPlottable(new PlaneParametricFunction2(new MultivariateVectorialFunction(){
            public double[] value(double[] point) throws FunctionEvaluationException, IllegalArgumentException {
                return new double[]{
                    point[0]*point[1], Math.sin(point[0]+point[1]) * Math.exp(point[0])
                };
            }
        }, new Point2D.Double(1,1), new Point2D.Double(3,3)));
        funPlot2.setDesiredRange(-3.0, -3.0, 3.0, 3.0);


        // PANELS

        rollupPanel1.add("Visometry", new PropertySheet(basicPlot.getVisometry()));
        for (Plottable p : basicPlot.getPlottables()) {
            rollupPanel1.add(p.toString(), new PropertySheet(p));
        }
//        rollupPanel1.add("Point Style", new PropertySheet(planePlotComponent1.getVisometryGraphics().getPointStyle()));
//        rollupPanel1.add("Stroke Style", new PropertySheet(planePlotComponent1.getVisometryGraphics().getPathStyle()));
//        rollupPanel1.add("Text Style", new PropertySheet(planePlotComponent1.getVisometryGraphics().getTextStyle()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        rollupPanel1 = new gui.RollupPanel();
        tabPane = new javax.swing.JTabbedPane();
        basicPlot = new org.bm.blaise.specto.plane.PlanePlotComponent();
        funPlot = new org.bm.blaise.specto.plane.PlanePlotComponent();
        funPlot2 = new org.bm.blaise.specto.plane.PlanePlotComponent();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jToolBar1.setRollover(true);

        jButton1.setText("jButton1");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setViewportView(rollupPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.EAST);

        tabPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabPaneStateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout basicPlotLayout = new org.jdesktop.layout.GroupLayout(basicPlot);
        basicPlot.setLayout(basicPlotLayout);
        basicPlotLayout.setHorizontalGroup(
            basicPlotLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 567, Short.MAX_VALUE)
        );
        basicPlotLayout.setVerticalGroup(
            basicPlotLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 370, Short.MAX_VALUE)
        );

        tabPane.addTab("BasicPlot", basicPlot);

        org.jdesktop.layout.GroupLayout funPlotLayout = new org.jdesktop.layout.GroupLayout(funPlot);
        funPlot.setLayout(funPlotLayout);
        funPlotLayout.setHorizontalGroup(
            funPlotLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 567, Short.MAX_VALUE)
        );
        funPlotLayout.setVerticalGroup(
            funPlotLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 370, Short.MAX_VALUE)
        );

        tabPane.addTab("FuncPlot", funPlot);

        org.jdesktop.layout.GroupLayout funPlot2Layout = new org.jdesktop.layout.GroupLayout(funPlot2);
        funPlot2.setLayout(funPlot2Layout);
        funPlot2Layout.setHorizontalGroup(
            funPlot2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 567, Short.MAX_VALUE)
        );
        funPlot2Layout.setVerticalGroup(
            funPlot2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 370, Short.MAX_VALUE)
        );

        tabPane.addTab("FuncPlot2", funPlot2);

        getContentPane().add(tabPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println("Here");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabPaneStateChanged
        rollupPanel1.removeAll();
        PlanePlotComponent ppc = (PlanePlotComponent) tabPane.getSelectedComponent();
        rollupPanel1.add("Visometry", new PropertySheet(ppc.getVisometry()));
        for (Plottable p : ppc.getPlottables()) {
            rollupPanel1.add(p.toString(), new PropertySheet(p));
        }
}//GEN-LAST:event_tabPaneStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TestBasicPlane().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.bm.blaise.specto.plane.PlanePlotComponent basicPlot;
    private org.bm.blaise.specto.plane.PlanePlotComponent funPlot;
    private org.bm.blaise.specto.plane.PlanePlotComponent funPlot2;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private gui.RollupPanel rollupPanel1;
    private javax.swing.JTabbedPane tabPane;
    // End of variables declaration//GEN-END:variables
}
