/*
 * TestPlaneVisometry.java
 *
 * Created on Jul 30, 2009, 3:15:03 PM
 */
package org.bm.blaise.testing.plane;

import org.apache.commons.math.FunctionEvaluationException;
import org.bm.blaise.specto.plane.data._SpacedPaths;
import org.bm.blaise.specto.plane.data.PlaneInterpolatingFunction;
import data.propertysheet.PropertySheet;
import java.awt.geom.Point2D;
import org.apache.commons.math.analysis.UnivariateRealFunction;
import org.bm.blaise.specto.plane.PlaneAxes;
import org.bm.blaise.specto.plane.PlaneGrid;
import org.bm.blaise.specto.plane.PlanePlotComponent;
import org.bm.blaise.specto.plane.diffeq.PlaneCobwebFunction;
import org.bm.blaise.specto.plane.function.PlaneFunctionGraph;
import org.bm.blaise.specto.plane.random.PlaneRandomWalk;
import org.bm.blaise.specto.visometry.Plottable;
import scio.diffeq.DifferenceEquation1;

/**
 *
 * @author ae3263
 */
public class TestPlaneVisometry extends javax.swing.JFrame {


    /** Creates new form TestPlaneVisometry */
    public TestPlaneVisometry() {
        data.beans.EditorRegistration.registerEditors();
        initComponents();

        interPlot.addPlottable(new PlaneGrid());
        interPlot.addPlottable(new PlaneInterpolatingFunction(new Point2D.Double[]{
                    new Point2D.Double(), new Point2D.Double(.25, .25), new Point2D.Double(.5, .5), new Point2D.Double(.75, .75), new Point2D.Double(1, 1)
                }));

        testPlot.addPlottable(new PlaneGrid());
        testPlot.addPlottable(new PlaneAxes());
        testPlot.addPlottable(new _SpacedPaths());

        randPlot.addPlottable(new PlaneGrid());
        randPlot.addPlottable(new PlaneRandomWalk(new Point2D.Double()));


        // PANELS

        rollupPanel1.add("Visometry", new PropertySheet(interPlot.getVisometry()));
        for (Plottable p : interPlot.getPlottables()) {
            rollupPanel1.add(p.toString(), new PropertySheet(p));
        }
//        rollupPanel1.add("Point Style", new PropertySheet(planePlotComponent1.getVisometryGraphics().getPointStyle()));
//        rollupPanel1.add("Stroke Style", new PropertySheet(planePlotComponent1.getVisometryGraphics().getPathStyle()));
//        rollupPanel1.add("Text Style", new PropertySheet(planePlotComponent1.getVisometryGraphics().getTextStyle()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        rollupPanel1 = new gui.RollupPanel();
        tabPane = new javax.swing.JTabbedPane();
        interPlot = new org.bm.blaise.specto.plane.PlanePlotComponent();
        randPlot = new org.bm.blaise.specto.plane.PlanePlotComponent();
        testPlot = new org.bm.blaise.specto.plane.PlanePlotComponent();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jToolBar1.setRollover(true);

        jButton1.setText("jButton1");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setViewportView(rollupPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.EAST);

        tabPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabPaneStateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout interPlotLayout = new org.jdesktop.layout.GroupLayout(interPlot);
        interPlot.setLayout(interPlotLayout);
        interPlotLayout.setHorizontalGroup(
            interPlotLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 567, Short.MAX_VALUE)
        );
        interPlotLayout.setVerticalGroup(
            interPlotLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 370, Short.MAX_VALUE)
        );

        tabPane.addTab("Interpolating", interPlot);

        org.jdesktop.layout.GroupLayout randPlotLayout = new org.jdesktop.layout.GroupLayout(randPlot);
        randPlot.setLayout(randPlotLayout);
        randPlotLayout.setHorizontalGroup(
            randPlotLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 567, Short.MAX_VALUE)
        );
        randPlotLayout.setVerticalGroup(
            randPlotLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 370, Short.MAX_VALUE)
        );

        tabPane.addTab("Random Walk", randPlot);

        org.jdesktop.layout.GroupLayout testPlotLayout = new org.jdesktop.layout.GroupLayout(testPlot);
        testPlot.setLayout(testPlotLayout);
        testPlotLayout.setHorizontalGroup(
            testPlotLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 567, Short.MAX_VALUE)
        );
        testPlotLayout.setVerticalGroup(
            testPlotLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 370, Short.MAX_VALUE)
        );

        tabPane.addTab("Testing", testPlot);

        getContentPane().add(tabPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println("Here");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabPaneStateChanged
        rollupPanel1.removeAll();
        PlanePlotComponent ppc = (PlanePlotComponent) tabPane.getSelectedComponent();
        rollupPanel1.add("Visometry", new PropertySheet(ppc.getVisometry()));
        for (Plottable p : ppc.getPlottables()) {
            rollupPanel1.add(p.toString(), new PropertySheet(p));
        }
}//GEN-LAST:event_tabPaneStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TestPlaneVisometry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.bm.blaise.specto.plane.PlanePlotComponent interPlot;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private org.bm.blaise.specto.plane.PlanePlotComponent randPlot;
    private gui.RollupPanel rollupPanel1;
    private javax.swing.JTabbedPane tabPane;
    private org.bm.blaise.specto.plane.PlanePlotComponent testPlot;
    // End of variables declaration//GEN-END:variables
}
