/*
 * AVectorField.java
 *
 * Created on October 29, 2008, 6:51 AM
 */

package curro;

import java.util.Vector;
import sequor.control.NumberSlider;
import specto.euclidean2.DESolution2D;
import specto.euclidean2.Parametric2D;
import specto.euclidean3.ParametricSurface3D;

/**
 *
 * @author  ae3263
 */
public class AParametricSurface extends javax.swing.JApplet {

    /** Initializes the applet AVectorField */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                    Vector<String> vars = new Vector<String>();
                    vars.add("u"); vars.add("v");
                    functionPanel1.getFunctionModel(0).getRoot().setVariables(vars);
                    functionPanel1.getFunctionModel(1).getRoot().setVariables(vars);
                    functionPanel1.getFunctionModel(2).getRoot().setVariables(vars);
                    functionPanel1.setFunction(0, "x(u,v)=", "cos(u)*sin(v)");
                    functionPanel1.setFunction(1, "y(u,v)=", "sin(u)*sin(v)");
                    functionPanel1.setFunction(2, "z(u,v)=", "cos(v)");
                    ParametricSurface3D ps1 = new ParametricSurface3D(
                            functionPanel1.getFunctionModel(0),
                            functionPanel1.getFunctionModel(1),
                            functionPanel1.getFunctionModel(2));  
                    ps1.getDomainModel().xModel.setRangeProperties(0.0, 0.0, 2*Math.PI, Math.PI/12);
                    ps1.getDomainModel().yModel.setRangeProperties(0.0, 0.0, Math.PI/3, Math.PI/12);
                    
                    plot3D1.add(ps1);
                    plot3D1.getVisometry().setSceneSize(3.0);
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vectorField2D1 = new specto.euclidean2.VectorField2D();
        jSplitPane1 = new javax.swing.JSplitPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        functionPanel1 = new sequor.component.FunctionPanel(3);
        functionPanel2 = new sequor.component.FunctionPanel(2);
        plot3D1 = new specto.euclidean3.Plot3D();

        jSplitPane1.setDividerLocation(125);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jTabbedPane2.addTab("Surface", functionPanel1);
        jTabbedPane2.addTab("Vector Field", functionPanel2);

        jSplitPane1.setLeftComponent(jTabbedPane2);

        javax.swing.GroupLayout plot3D1Layout = new javax.swing.GroupLayout(plot3D1);
        plot3D1.setLayout(plot3D1Layout);
        plot3D1Layout.setHorizontalGroup(
            plot3D1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );
        plot3D1Layout.setVerticalGroup(
            plot3D1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 261, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(plot3D1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sequor.component.FunctionPanel functionPanel1;
    private sequor.component.FunctionPanel functionPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private specto.euclidean3.Plot3D plot3D1;
    private specto.euclidean2.VectorField2D vectorField2D1;
    // End of variables declaration//GEN-END:variables

}
