/*
 * AVectorField.java
 *
 * Created on October 29, 2008, 6:51 AM
 */

package curro;

import sequor.control.NumberSlider;
import specto.euclidean3.DESolution3D;
import specto.euclidean3.ParametricCurve3D;
import specto.euclidean3.VectorField3D;

/**
 *
 * @author  ae3263
 */
public class AVectorField3D extends javax.swing.JApplet {

    /** Initializes the applet AVectorField */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                    functionPanel1.setFunction(0, "P(x,y,z)=", "-y");
                    functionPanel1.setFunction(1, "Q(x,y,z)=", "x");
                    functionPanel1.setFunction(2, "R(x,y,z)=", "1-z");
                    VectorField3D vf1=new VectorField3D(functionPanel1.getFunctionModel(0),functionPanel1.getFunctionModel(1),functionPanel1.getFunctionModel(2));                        
                    
                    plot3D1.add(vf1);
                    DESolution3D des = new DESolution3D(vf1);
                    des.setVisible(false);
                    plot3D1.add(des);
                    NumberSlider ns = vf1.getStyleSlider(0,0);
                    ns.setName("Style");
                    plot3D1.add(ns,5,5);
                        
                    functionPanel2.setFunction(0, "x(t)=", "cos(t)+3");
                    functionPanel2.setFunction(1, "y(t)=", "sin(t)+3");
                    functionPanel2.setFunction(2, "y(t)=", "t");
                    ParametricCurve3D pp = new ParametricCurve3D(functionPanel2.getFunctionModel(0),functionPanel2.getFunctionModel(1),functionPanel2.getFunctionModel(2));
                    pp.setVisible(false);
                    pp.setAnimationOn(false);
                    plot3D1.add(pp);     
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vectorField2D1 = new specto.euclidean2.VectorField2D();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        functionPanel1 = new sequor.component.FunctionPanel(3);
        functionPanel2 = new sequor.component.FunctionPanel(3);
        plot3D1 = new specto.euclidean3.Plot3D();

        jSplitPane1.setDividerLocation(125);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jTabbedPane2.addTab("Vector Field", functionPanel1);
        jTabbedPane2.addTab("Curve", functionPanel2);

        jSplitPane1.setLeftComponent(jTabbedPane2);

        javax.swing.GroupLayout plot3D1Layout = new javax.swing.GroupLayout(plot3D1);
        plot3D1.setLayout(plot3D1Layout);
        plot3D1Layout.setHorizontalGroup(
            plot3D1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );
        plot3D1Layout.setVerticalGroup(
            plot3D1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 261, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(plot3D1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sequor.component.FunctionPanel functionPanel1;
    private sequor.component.FunctionPanel functionPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private specto.euclidean3.Plot3D plot3D1;
    private specto.euclidean2.VectorField2D vectorField2D1;
    // End of variables declaration//GEN-END:variables

}
