/*
 * BasicPlotter.java
 *
 * Created on September 12, 2007, 9:45 AM
 */

package curro;

/**
 *
 * @author  ae3263
 */
public class BasicPlotterApplet extends javax.swing.JApplet {
    
    /** Initializes the applet BasicPlotter */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                    functionField1.setText("cos(x)-x^2/20");
                    function2D1.setFunction(functionField1.getFunction());
                    plot2D1.add(function2D1);
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        function2D1 = new specto.dynamicplottable.Function2D();
        jLabel1 = new javax.swing.JLabel();
        functionField1 = new sequor.component.FunctionField();
        plot2D1 = new specto.plotpanel.Plot2D();

        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("f(x)=");

        functionField1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                functionField1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout plot2D1Layout = new javax.swing.GroupLayout(plot2D1);
        plot2D1.setLayout(plot2D1Layout);
        plot2D1Layout.setHorizontalGroup(
            plot2D1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );
        plot2D1Layout.setVerticalGroup(
            plot2D1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(functionField1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
            .addComponent(plot2D1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(plot2D1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(functionField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void functionField1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_functionField1StateChanged
        function2D1.setFunction(functionField1.getFunction());
        plot2D1.repaint();
    }//GEN-LAST:event_functionField1StateChanged
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private specto.dynamicplottable.Function2D function2D1;
    private sequor.component.FunctionField functionField1;
    private javax.swing.JLabel jLabel1;
    private specto.plotpanel.Plot2D plot2D1;
    // End of variables declaration//GEN-END:variables
    
}
