/*
 * MultiPlotter.java
 *
 * Created on November 13, 2007, 9:31 AM
 */

package curro;

import java.awt.Color;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import sequor.component.Settings;
import sequor.model.FunctionTreeModel;
import sequor.model.ParameterListModel;
import sequor.model.SettingsProperty;
import specto.plottable.Function2D;

/**
 *
 * @author  ae3263
 */
public class MultiPlotter extends javax.swing.JFrame {
    FunctionTreeModel ftm,ftm2;
    ParameterListModel plm;
        
    /** Creates new form MultiPlotter */
    public MultiPlotter() {
        plm=new ParameterListModel();
        plm.addChangeListener(new ChangeListener(){
            public void stateChanged(ChangeEvent e) {
                if((e.getSource() instanceof ParameterListModel)&&(((ParameterListModel)plm).isAdded())){
                    ((ParameterListModel)plm).updatePanel(jPanel2);
                }
            }
        });    
        initComponents();  
        ftm=new FunctionTreeModel("a*sin(b*(x-c))+d","x");
        ftm2=new FunctionTreeModel(ftm.getRoot().derivativeTree("x").fullSimplified());
        ftm.addChangeListener(new ChangeListener(){
            public void stateChanged(ChangeEvent e){ 
                try{
                    ftm2.setValue(ftm.getRoot().derivativeTree("x").fullSimplified().toString());
                }catch(NullPointerException exc){}
            }
        });
        plot2D1.add(new Function2D(ftm2,Color.lightGray));
        plot2D1.add(new Function2D(ftm));
        plm.addChangeListener(ftm);  
        plm.addChangeListener(ftm2);
        plm.setParameterValue("a",1.0);
        plm.setParameterValue("b",2.0);
        plm.setParameterValue("c",Math.PI/2);
        plm.setParameterValue("d",-1.0);
        Settings s=new Settings();
        s.addProperty("f(x)=",ftm,Settings.EDIT_FUNCTION);
        s.addProperty("f'(x)=",ftm2,Settings.EDIT_FUNCTION);
        s.initPanel(jPanel1);
        plot2D1.repaint();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plot2D1 = new specto.plotpanel.Plot2D();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = plm.getPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        plot2D1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(plot2D1, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultiPlotter().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private specto.plotpanel.Plot2D plot2D1;
    // End of variables declaration//GEN-END:variables
    
}
