/*
 * AParameterPlotter.java
 *
 * Created on November 7, 2008, 12:11 PM
 */

package curro;

import sequor.model.ParameterListModel;
import specto.euclidean3.ParametricSurface3D;
import specto.euclidean3.VectorField3D;

/**
 *
 * @author  ae3263
 */
public class PAFluxPlotter extends javax.swing.JApplet {
    
    String[][] functions = { 
        { "P(x,y,z)=" , "x*y", "x", "y", "z" },  { "Q(x,y,z)=" , "y*z", "x", "y", "z" },  { "R(x,y,z)=" , "-y/5", "x", "y", "z" },
        { "rx(u,v)=" , "a cos(u) sin(v)", "u", "v" }, { "ry(u,v)=" , "a sin(u) sin(v)", "u", "v" }, { "rz(u,v)=" , "a cos(v)", "u", "v" }
                };
    Object[][] parameters = { { "a", 1.0 }, { "b", 1.0 }, { "c", 0.0 }, { "d", -1.0 } };

    /** Initializes the applet AParameterPlotter */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
       
                    parameterListModel1=new ParameterListModel(parameters, settingsPanel1, functionPanel1);
                    plot3D1.add(new VectorField3D(functionPanel1.getFunctionModel(0), functionPanel1.getFunctionModel(1), functionPanel1.getFunctionModel(2)));
                    plot3D1.add(new ParametricSurface3D(functionPanel1.getFunctionModel(3), functionPanel1.getFunctionModel(4), functionPanel1.getFunctionModel(5)));
                    //plot2D1.add(new PlaneFunction2D(functionPanel1.getFunctionModel(0)));
                    //plot2D1.repaint();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parameterListModel1 = new sequor.model.ParameterListModel();
        settingsPanel1 = new sequor.component.SettingsPanel();
        functionPanel1 = new sequor.component.FunctionPanel(functions);
        plot3D1 = new specto.euclidean3.Plot3D();

        settingsPanel1.setPreferredSize(new java.awt.Dimension(202, 332));
        getContentPane().add(settingsPanel1, java.awt.BorderLayout.LINE_END);
        getContentPane().add(functionPanel1, java.awt.BorderLayout.PAGE_END);

        plot3D1.setAxisStyle(0);
        plot3D1.setXyStyle(3);

        javax.swing.GroupLayout plot3D1Layout = new javax.swing.GroupLayout(plot3D1);
        plot3D1.setLayout(plot3D1Layout);
        plot3D1Layout.setHorizontalGroup(
            plot3D1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );
        plot3D1Layout.setVerticalGroup(
            plot3D1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );

        getContentPane().add(plot3D1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sequor.component.FunctionPanel functionPanel1;
    private sequor.model.ParameterListModel parameterListModel1;
    private specto.euclidean3.Plot3D plot3D1;
    private sequor.component.SettingsPanel settingsPanel1;
    // End of variables declaration//GEN-END:variables

}
