/*
 * ParameterPlotter.java
 *
 * Created on November 13, 2007, 9:31 AM
 */

package curro;

import java.awt.Color;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import sequor.Settings;
import sequor.model.FunctionTreeModel;
import sequor.model.ParameterListModel;
import sequor.SettingsProperty;
import specto.euclidean2.Function2D;

/**
 *
 * @author  ae3263
 */
public class ParameterPlotter extends javax.swing.JFrame {
    FunctionTreeModel ftm,ftm2;
    ParameterListModel plm;
        
    /** Creates new form ParameterPlotter */
    public ParameterPlotter() {
        plm=new ParameterListModel();
        plm.addChangeListener(new ChangeListener(){
            public void stateChanged(ChangeEvent e) {
                if((e.getSource() instanceof ParameterListModel)&&(((ParameterListModel)plm).isAdded())){
                    ((ParameterListModel)plm).updatePanel(settingsPanel2);
                }
            }
        });    
        initComponents();  
        ftm=new FunctionTreeModel("a*sin(b*(x-c))+d","x");
        ftm2=new FunctionTreeModel(ftm.getRoot().derivativeTree("x").fullSimplified());
        ftm.addChangeListener(new ChangeListener(){
            public void stateChanged(ChangeEvent e){ 
                try{
                    ftm2.setValue(ftm.getRoot().derivativeTree("x").fullSimplified().toString());
                }catch(NullPointerException exc){}
                //settingsBar1.validate();
            }
        });
        plm.addChangeListener(ftm);  
        plm.addChangeListener(ftm2);
        plm.setParameterValue("a",1.0);
        plm.setParameterValue("b",2.0);
        plm.setParameterValue("c",Math.PI/2);
        plm.setParameterValue("d",-1.0);
        settings1.addProperty("f(x)=",ftm,Settings.EDIT_FUNCTION);
        settings1.addProperty("f'(x)=",ftm2,Settings.EDIT_FUNCTION);
        //settingsBar1.updateBar();
        
        plot2D1.add(new Function2D(ftm2,Color.lightGray));
        Function2D f1 = new Function2D(ftm);
        plot2D1.add(f1);
        plot2D1.add(f1.getPointSlope());
        plot2D1.repaint();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settings1 = new sequor.Settings();
        settings2 = new sequor.Settings();
        settingsPanel2 = new sequor.component.SettingsPanel(settings2);
        plot2D4 = new specto.euclidean2.Plot2D();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Function Plotter with Parameters");
        setMinimumSize(new java.awt.Dimension(600, 300));

        settingsPanel2.setPreferredSize(new java.awt.Dimension(152, 302));
        getContentPane().add(settingsPanel2, java.awt.BorderLayout.LINE_END);
        getContentPane().add(plot2D4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParameterPlotter().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private specto.euclidean2.Plot2D plot2D1;
    private specto.euclidean2.Plot2D plot2D2;
    private specto.euclidean2.Plot2D plot2D3;
    private specto.euclidean2.Plot2D plot2D4;
    private sequor.Settings settings1;
    private sequor.Settings settings2;
    private sequor.component.SettingsPanel settingsPanel2;
    // End of variables declaration//GEN-END:variables
    
}
