/*
 * AParameterPlotter.java
 *
 * Created on November 7, 2008, 12:11 PM
 */

package curro;

import sequor.model.ParameterListModel;
import specto.euclidean3.DESolution3D;
import specto.euclidean3.VectorField3D;

/**
 *
 * @author  ae3263
 */
public class PAVectorField3DPlotter extends javax.swing.JApplet {
    
    String[][] functions = { { "P(x,y,z)=" , "sigma*(y-x)", "x", "y", "z" }, { "Q(x,y,z)=", "(x*(10*rho-z)-y)", "x", "y", "z" }, { "R(x,y,z)=", "(x*y-beta*z)", "x", "y", "z" } };
    Object[][] parameters = { { "sigma", 10.0 }, { "beta", 2.33333 }, { "rho", 4.0 } };

    /** Initializes the applet AParameterPlotter */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
       
                    parameterListModel1=new ParameterListModel(parameters, settingsPanel1, functionPanel1);
                    VectorField3D vf1 = new VectorField3D(functionPanel1.getFunctionModel(0), functionPanel1.getFunctionModel(1), functionPanel1.getFunctionModel(2));
                    vf1.style.setValue(3);
                    plot3D1.add(vf1);
                    
                    DESolution3D de1 = new DESolution3D(vf1,.2,.3,.4);
                    de1.setNumSteps(2000);
                    de1.setStepSize(.5);
                    plot3D1.add(de1);

                    plot3D1.add(vf1.getStyleSlider("Field style",0,0),5,5);
                    plot3D1.getVisometry().setSceneSize(40.0);
                    plot3D1.getVisometry().setViewDist(100.0);
                    plot3D1.getVisometry().setDesiredBounds(-140.0,-140.0,140.0,140.0);
                    plot3D1.repaint();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parameterListModel1 = new sequor.model.ParameterListModel();
        settingsPanel1 = new sequor.component.SettingsPanel();
        functionPanel1 = new sequor.component.FunctionPanel(functions);
        plot3D1 = new specto.euclidean3.Plot3D();

        settingsPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Parameters"));
        settingsPanel1.setPreferredSize(new java.awt.Dimension(250, 332));
        getContentPane().add(settingsPanel1, java.awt.BorderLayout.LINE_END);
        getContentPane().add(functionPanel1, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout plot3D1Layout = new javax.swing.GroupLayout(plot3D1);
        plot3D1.setLayout(plot3D1Layout);
        plot3D1Layout.setHorizontalGroup(
            plot3D1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );
        plot3D1Layout.setVerticalGroup(
            plot3D1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        getContentPane().add(plot3D1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sequor.component.FunctionPanel functionPanel1;
    private sequor.model.ParameterListModel parameterListModel1;
    private specto.euclidean3.Plot3D plot3D1;
    private sequor.component.SettingsPanel settingsPanel1;
    // End of variables declaration//GEN-END:variables

}
