package specto.euclidean3;

/*
 * BlaisePlotter.java
 *
 * Created on November 9, 2007, 1:36 PM
 */


import javax.swing.event.ChangeEvent;
import specto.euclidean3.VectorField3D;
import specto.euclidean3.PlaneFunction3D;
import specto.euclidean3.DESolution3D;
import sequor.control.SliderBox;

/**
 *
 * @author  ae3263
 */
public class TestPlottables3 extends javax.swing.JFrame {
    
    /** Creates new form BlaisePlotter */
    public TestPlottables3() {
        initComponents();
        
        PlaneFunction3D pf = new PlaneFunction3D();
        defaultPlot.add(pf);
        defaultPlot.add(SliderBox.getStyleAdjusters(100,10,15,defaultPlot.getPlottables(),defaultPlot));
        
        VectorField3D vf3 = new VectorField3D();
        vectorFieldPlot.add(vf3);
        vectorFieldPlot.add(new DESolution3D(vf3));
        vectorFieldPlot.add(SliderBox.getStyleAdjusters(100,10,15,vectorFieldPlot.getPlottables(),vectorFieldPlot));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        defaultPlot = new specto.euclidean3.Plot3D();
        vectorFieldPlot = new specto.euclidean3.Plot3D();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        menuBar1 = new javax.swing.JMenuBar();
        fileMenu1 = new javax.swing.JMenu();
        openMenuItem1 = new javax.swing.JMenuItem();
        saveMenuItem1 = new javax.swing.JMenuItem();
        saveAsMenuItem1 = new javax.swing.JMenuItem();
        exitMenuItem1 = new javax.swing.JMenuItem();
        editMenu1 = new javax.swing.JMenu();
        cutMenuItem1 = new javax.swing.JMenuItem();
        copyMenuItem1 = new javax.swing.JMenuItem();
        pasteMenuItem1 = new javax.swing.JMenuItem();
        deleteMenuItem1 = new javax.swing.JMenuItem();
        helpMenu1 = new javax.swing.JMenu();
        contentsMenuItem1 = new javax.swing.JMenuItem();
        aboutMenuItem1 = new javax.swing.JMenuItem();
        menuBar2 = new javax.swing.JMenuBar();
        fileMenu2 = new javax.swing.JMenu();
        openMenuItem2 = new javax.swing.JMenuItem();
        saveMenuItem2 = new javax.swing.JMenuItem();
        saveAsMenuItem2 = new javax.swing.JMenuItem();
        exitMenuItem2 = new javax.swing.JMenuItem();
        editMenu2 = new javax.swing.JMenu();
        cutMenuItem2 = new javax.swing.JMenuItem();
        copyMenuItem2 = new javax.swing.JMenuItem();
        pasteMenuItem2 = new javax.swing.JMenuItem();
        deleteMenuItem2 = new javax.swing.JMenuItem();
        helpMenu2 = new javax.swing.JMenu();
        contentsMenuItem2 = new javax.swing.JMenuItem();
        aboutMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Demo of 2D Plottables");

        javax.swing.GroupLayout defaultPlotLayout = new javax.swing.GroupLayout(defaultPlot);
        defaultPlot.setLayout(defaultPlotLayout);
        defaultPlotLayout.setHorizontalGroup(
            defaultPlotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 669, Short.MAX_VALUE)
        );
        defaultPlotLayout.setVerticalGroup(
            defaultPlotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        tabs.addTab("General", defaultPlot);

        javax.swing.GroupLayout vectorFieldPlotLayout = new javax.swing.GroupLayout(vectorFieldPlot);
        vectorFieldPlot.setLayout(vectorFieldPlotLayout);
        vectorFieldPlotLayout.setHorizontalGroup(
            vectorFieldPlotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 669, Short.MAX_VALUE)
        );
        vectorFieldPlotLayout.setVerticalGroup(
            vectorFieldPlotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        tabs.addTab("Vector Field", vectorFieldPlot);

        fileMenu.setText("File"); // NOI18N

        openMenuItem.setText("Open"); // NOI18N
        fileMenu.add(openMenuItem);

        saveMenuItem.setText("Save"); // NOI18N
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setText("Save As ..."); // NOI18N
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setText("Exit"); // NOI18N
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setText("Edit"); // NOI18N

        cutMenuItem.setText("Cut"); // NOI18N
        editMenu.add(cutMenuItem);

        copyMenuItem.setText("Copy"); // NOI18N
        editMenu.add(copyMenuItem);

        pasteMenuItem.setText("Paste"); // NOI18N
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setText("Delete"); // NOI18N
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setText("Help"); // NOI18N

        contentsMenuItem.setText("Contents"); // NOI18N
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setText("About"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        fileMenu1.setText("File"); // NOI18N

        openMenuItem1.setText("Open"); // NOI18N
        fileMenu1.add(openMenuItem1);

        saveMenuItem1.setText("Save"); // NOI18N
        fileMenu1.add(saveMenuItem1);

        saveAsMenuItem1.setText("Save As ..."); // NOI18N
        fileMenu1.add(saveAsMenuItem1);

        exitMenuItem1.setText("Exit"); // NOI18N
        exitMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu1.add(exitMenuItem1);

        menuBar1.add(fileMenu1);

        editMenu1.setText("Edit"); // NOI18N

        cutMenuItem1.setText("Cut"); // NOI18N
        editMenu1.add(cutMenuItem1);

        copyMenuItem1.setText("Copy"); // NOI18N
        editMenu1.add(copyMenuItem1);

        pasteMenuItem1.setText("Paste"); // NOI18N
        editMenu1.add(pasteMenuItem1);

        deleteMenuItem1.setText("Delete"); // NOI18N
        editMenu1.add(deleteMenuItem1);

        menuBar1.add(editMenu1);

        helpMenu1.setText("Help"); // NOI18N

        contentsMenuItem1.setText("Contents"); // NOI18N
        helpMenu1.add(contentsMenuItem1);

        aboutMenuItem1.setText("About"); // NOI18N
        helpMenu1.add(aboutMenuItem1);

        menuBar1.add(helpMenu1);

        fileMenu2.setText("File"); // NOI18N

        openMenuItem2.setText("Open"); // NOI18N
        fileMenu2.add(openMenuItem2);

        saveMenuItem2.setText("Save"); // NOI18N
        fileMenu2.add(saveMenuItem2);

        saveAsMenuItem2.setText("Save As ..."); // NOI18N
        fileMenu2.add(saveAsMenuItem2);

        exitMenuItem2.setText("Exit"); // NOI18N
        exitMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu2.add(exitMenuItem2);

        menuBar2.add(fileMenu2);

        editMenu2.setText("Edit"); // NOI18N

        cutMenuItem2.setText("Cut"); // NOI18N
        editMenu2.add(cutMenuItem2);

        copyMenuItem2.setText("Copy"); // NOI18N
        editMenu2.add(copyMenuItem2);

        pasteMenuItem2.setText("Paste"); // NOI18N
        editMenu2.add(pasteMenuItem2);

        deleteMenuItem2.setText("Delete"); // NOI18N
        editMenu2.add(deleteMenuItem2);

        menuBar2.add(editMenu2);

        helpMenu2.setText("Help"); // NOI18N

        contentsMenuItem2.setText("Contents"); // NOI18N
        helpMenu2.add(contentsMenuItem2);

        aboutMenuItem2.setText("About"); // NOI18N
        helpMenu2.add(aboutMenuItem2);

        menuBar2.add(helpMenu2);

        setJMenuBar(menuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestPlottables3().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem aboutMenuItem1;
    private javax.swing.JMenuItem aboutMenuItem2;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem contentsMenuItem1;
    private javax.swing.JMenuItem contentsMenuItem2;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem copyMenuItem1;
    private javax.swing.JMenuItem copyMenuItem2;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem cutMenuItem1;
    private javax.swing.JMenuItem cutMenuItem2;
    private specto.euclidean3.Plot3D defaultPlot;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenuItem deleteMenuItem1;
    private javax.swing.JMenuItem deleteMenuItem2;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu editMenu1;
    private javax.swing.JMenu editMenu2;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem exitMenuItem1;
    private javax.swing.JMenuItem exitMenuItem2;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu fileMenu1;
    private javax.swing.JMenu fileMenu2;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu helpMenu1;
    private javax.swing.JMenu helpMenu2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuBar menuBar1;
    private javax.swing.JMenuBar menuBar2;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem openMenuItem1;
    private javax.swing.JMenuItem openMenuItem2;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem pasteMenuItem1;
    private javax.swing.JMenuItem pasteMenuItem2;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem1;
    private javax.swing.JMenuItem saveAsMenuItem2;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JMenuItem saveMenuItem1;
    private javax.swing.JMenuItem saveMenuItem2;
    private javax.swing.JTabbedPane tabs;
    private specto.euclidean3.Plot3D vectorFieldPlot;
    // End of variables declaration//GEN-END:variables
    
}
