/*
 * TestPlaneVisometry.java
 *
 * Created on Jul 30, 2009, 3:15:03 PM
 */
package org.bm.blaise.testing.space;

import org.bm.blaise.testing.plane.*;
import data.propertysheet.PropertySheet;
import java.awt.geom.Point2D;
import org.apache.commons.math.FunctionEvaluationException;
import org.apache.commons.math.analysis.MultivariateVectorialFunction;
import org.apache.commons.math.analysis.UnivariateVectorialFunction;
import org.bm.blaise.specto.line.LineAxes;
import org.bm.blaise.specto.plane.PlaneAxes;
import org.bm.blaise.specto.plane.PlaneGrid;
import org.bm.blaise.specto.plane.PlanePlotComponent;
import org.bm.blaise.specto.plane.PlanePolarGrid;
import org.bm.blaise.specto.plane.function.PlaneParametricArea;
import org.bm.blaise.specto.plane.function.PlaneParametricCurve;
import org.bm.blaise.specto.space.SpaceAxes;
import org.bm.blaise.specto.space.SpacePlotComponent;
import org.bm.blaise.specto.space.function.SpaceParametricCurve;
import org.bm.blaise.specto.space.function.SpaceParametricSurface;
import org.bm.blaise.specto.visometry.Plottable;
import scio.function.utils.SampleSurface3D;

/**
 *
 * @author ae3263
 */
public class TestSpaceParametricPlottables extends javax.swing.JFrame {

    /** Creates new form TestPlaneVisometry */
    public TestSpaceParametricPlottables() {
        data.beans.EditorRegistration.registerEditors();
        initComponents();


        // FUNCTIONS

        SpaceParametricCurve spc = new SpaceParametricCurve(
                new UnivariateVectorialFunction() {
                    public double[] value(double x) throws FunctionEvaluationException {
                        return new double[] { (2 + 1.1*Math.sin(7*x)) * Math.cos(2*x), (2 + 1.1*Math.sin(7*x)) * Math.sin(2*x), 1.1*Math.cos(7*x) };
                    }
                },
                0.0, 2*Math.PI, 200);
        SpaceParametricSurface sps = SpaceParametricSurface.getInstance(SampleSurface3D.SPHERE);

        domainPlot1.addPlottable(LineAxes.instance("t"));
        domainPlot1.addPlottable(spc.getDomainPlottable());

        rangePlot1.addPlottable(new SpaceAxes());
        rangePlot1.addPlottable(spc);

        domainPlot2.addPlottable(new PlaneGrid());
        domainPlot2.addPlottable(PlaneAxes.instance("u", "v"));
        domainPlot2.addPlottable(sps.getDomainPlottable());

        rangePlot2.addPlottable(new SpaceAxes());
        rangePlot2.addPlottable(sps);
        
        // PANELS

        rollupPanel1.add("Visometry", new PropertySheet(rangePlot1.getVisometry()));
        for (Plottable p : rangePlot1.getPlottables()) {
            rollupPanel1.add(p.toString(), new PropertySheet(p));
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        rollupPanel1 = new gui.RollupPanel();
        tabPane = new javax.swing.JTabbedPane();
        rangePlot1 = new org.bm.blaise.specto.space.SpacePlotComponent();
        rangePlot2 = new org.bm.blaise.specto.space.SpacePlotComponent();
        jPanel1 = new javax.swing.JPanel();
        domainPlot1 = new org.bm.blaise.specto.line.LinePlotComponent();
        domainPlot2 = new org.bm.blaise.specto.plane.PlanePlotComponent();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jToolBar1.setRollover(true);

        jButton1.setText("jButton1");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setViewportView(rollupPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.EAST);

        tabPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabPaneStateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout rangePlot1Layout = new org.jdesktop.layout.GroupLayout(rangePlot1);
        rangePlot1.setLayout(rangePlot1Layout);
        rangePlot1Layout.setHorizontalGroup(
            rangePlot1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 988, Short.MAX_VALUE)
        );
        rangePlot1Layout.setVerticalGroup(
            rangePlot1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 309, Short.MAX_VALUE)
        );

        tabPane.addTab("Parametric Curve", rangePlot1);

        org.jdesktop.layout.GroupLayout rangePlot2Layout = new org.jdesktop.layout.GroupLayout(rangePlot2);
        rangePlot2.setLayout(rangePlot2Layout);
        rangePlot2Layout.setHorizontalGroup(
            rangePlot2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 988, Short.MAX_VALUE)
        );
        rangePlot2Layout.setVerticalGroup(
            rangePlot2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 309, Short.MAX_VALUE)
        );

        tabPane.addTab("Parametric Surface", rangePlot2);

        getContentPane().add(tabPane, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        org.jdesktop.layout.GroupLayout domainPlot1Layout = new org.jdesktop.layout.GroupLayout(domainPlot1);
        domainPlot1.setLayout(domainPlot1Layout);
        domainPlot1Layout.setHorizontalGroup(
            domainPlot1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 501, Short.MAX_VALUE)
        );
        domainPlot1Layout.setVerticalGroup(
            domainPlot1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 200, Short.MAX_VALUE)
        );

        jPanel1.add(domainPlot1);

        org.jdesktop.layout.GroupLayout domainPlot2Layout = new org.jdesktop.layout.GroupLayout(domainPlot2);
        domainPlot2.setLayout(domainPlot2Layout);
        domainPlot2Layout.setHorizontalGroup(
            domainPlot2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 501, Short.MAX_VALUE)
        );
        domainPlot2Layout.setVerticalGroup(
            domainPlot2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 200, Short.MAX_VALUE)
        );

        jPanel1.add(domainPlot2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println("Here");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabPaneStateChanged
        rollupPanel1.removeAll();
        SpacePlotComponent ppc = (SpacePlotComponent) tabPane.getSelectedComponent();
        rollupPanel1.add("Visometry", new PropertySheet(ppc.getVisometry()));
        for (Plottable p : ppc.getPlottables()) {
            rollupPanel1.add(p.toString(), new PropertySheet(p));
        }
}//GEN-LAST:event_tabPaneStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TestSpaceParametricPlottables().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.bm.blaise.specto.line.LinePlotComponent domainPlot1;
    private org.bm.blaise.specto.plane.PlanePlotComponent domainPlot2;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private org.bm.blaise.specto.space.SpacePlotComponent rangePlot1;
    private org.bm.blaise.specto.space.SpacePlotComponent rangePlot2;
    private gui.RollupPanel rollupPanel1;
    private javax.swing.JTabbedPane tabPane;
    // End of variables declaration//GEN-END:variables
}
